import "./style.css";
// import { renderPrepCamera } from "./prepCamera";
// import { renderOrthoCamera } from "./orthoCamera";
// import { renderOrbitControls } from "./orbitControllers";
// import { fullScreenCanvas } from "./fullScreenCanvas";
// import { customGeometry } from "./costomGeometry";
// import { debugTools } from "./debugTools";
// import { textures } from "./textures";
// import { materials } from "./materials";
import { fontGeometry } from "./fontGeometry";

// renderPrepCamera();
// renderOrthoCamera();
// renderOrbitControls();
// fullScreenCanvas();
// customGeometry();
// debugTools();
// textures();
// materials();
fontGeometry();
